# Generated by Django 3.1.5 on 2021-01-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=220)),
                ('url', models.CharField(max_length=220)),
                ('urlToImage', models.CharField(max_length=220)),
                ('publishedAt', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=420)),
            ],
        ),
    ]
